# SQL Server (2005 or higher recommended)
#
# Install the adapters and driver
#   gem install tiny_tds
#   gem install activerecord-sqlserver-adapter
#
# Ensure the activerecord adapter and db driver gems are defined in your Gemfile
#   gem 'tiny_tds'
#   gem 'activerecord-sqlserver-adapter'
#
# You should make sure freetds is configured correctly first.
# freetds.conf contains host/port/protocol_versions settings.
# http://freetds.schemamania.org/userguide/freetdsconf.htm
#
# A typical Microsoft server
#   [mssql]
#   host = mssqlserver.yourdomain.com
#   port = 1433
#   tds version = 7.1

# If you can connect with "tsql -S servername", your basic FreeTDS installation is working.
# 'man tsql' for more info
# Set timeout to a larger number if valid queries against a live db fail

development:
  adapter: sqlserver
  encoding: utf8
  reconnect: false
  database: Gouda02_development
  username: sa
  password: dsa123
  timeout: 25
  dataserver: lgonzalez

test:
  adapter: sqlserver
  encoding: utf8
  reconnect: false
  database: Gouda02_test
  username: sa
  password: dsa123
  timeout: 25
  dataserver: lgonzalez

production:
  adapter: sqlserver
  encoding: utf8
  reconnect: false
  database: Gouda02_production
  username: sa
  password: dsa123
  timeout: 25
  dataserver: lgonzalez

